import os
import shutil
from typing import Callable


def if_missing(func: Callable, *paths: str, **keyword_paths: str):
    # TODO: need verbosity
    if not paths and not keyword_paths:
        raise ValueError('At least one path must be provided either via positional or keyword arguments.')

    outputs = paths + tuple(keyword_paths.values())
    if all(map(os.path.exists, outputs)):
        return

    try:
        # TODO: add lock?
        func(*paths, **keyword_paths)
    except BaseException as e:
        list(map(shutil.rmtree, filter(os.path.exists, outputs)))
        raise RuntimeError('An exception occurred. Cleaning up...\n') from e

    if not all(map(os.path.exists, outputs)):
        raise FileNotFoundError(f'One of the outputs was not generated by the given function: {", ".join(outputs)}')
