import os
import shutil
from typing import Callable


def if_missing(func: Callable, *paths: str, **keyword_paths: str):
    """
    Call `func` if at least some of the `paths` do not exist.

    Examples
    --------
    >>> if_missing(save_results, 'values', 'metrics', misc='temp_data')
    # if `values` or `metrics` or `temp_data` do not exist, the following call will be performed:
    >>> save_results('values', 'metrics', misc='temp_data')
    """
    outputs = paths + tuple(keyword_paths.values())
    if not outputs:
        raise ValueError('At least one path must be provided either via positional or keyword arguments.')

    if all(map(os.path.exists, outputs)):
        print(f'\n>>> Nothing to be done, all outputs already exist: {", ".join(outputs)}\n', flush=True)
        return

    print(f'\n>>> Running command to generate outputs: {", ".join(outputs)}\n', flush=True)

    try:
        func(*paths, **keyword_paths)
    except BaseException as e:
        list(map(shutil.rmtree, filter(os.path.exists, outputs)))
        raise RuntimeError('An exception occurred. Cleaning up...\n') from e

    missing = [path for path in outputs if not os.path.exists(path)]
    if missing:
        raise FileNotFoundError(f'The following outputs were not generated by the given function: {", ".join(missing)}')
